services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./packages/db/drizzle:/docker-entrypoint-initdb.d

volumes:
  pg_data:
